/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerScaleInjectables } from "./scale/register-injectables";
import roleBasedGroupSidebarItemInjectable from "./sidebar-item.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(roleBasedGroupSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerScaleInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
