/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import clearAiAgentTabDataInjectable from "./clear-ai-agent-tab-data.injectable";
import createAiAgentTabInjectable from "./create-ai-agent-tab.injectable";
import aiAgentTabStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(aiAgentTabStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(clearAiAgentTabDataInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createAiAgentTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
