/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import leaderWorkerSetScaleDialogStateInjectable from "./dialog-state.injectable";
import leaderWorkerSetScaleDialogClusterFrameChildComponentInjectable from "./leaderworkerset-scale-dialog-cluster-frame-child-component.injectable";
import openLeaderWorkerSetScaleDialogInjectable from "./open.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(leaderWorkerSetScaleDialogClusterFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(leaderWorkerSetScaleDialogStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openLeaderWorkerSetScaleDialogInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
