/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import roleBasedGroupScaleDialogStateInjectable from "./dialog-state.injectable";
import openRoleBasedGroupScaleDialogInjectable from "./open.injectable";
import roleBasedGroupScaleDialogClusterFrameChildComponentInjectable from "./rolebasedgroup-scale-dialog-cluster-frame-child-component.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(openRoleBasedGroupScaleDialogInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleBasedGroupScaleDialogClusterFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleBasedGroupScaleDialogStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
