/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import aiAgentPreferenceBlockInjectable from "./ai-agent-preference-block.injectable";
import aiAgentPreferencePageInjectable from "./ai-agent-preference-page.injectable";
import aiAgentPreferenceTabInjectable from "./ai-agent-preference-tab.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(aiAgentPreferenceBlockInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(aiAgentPreferencePageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(aiAgentPreferenceTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
