/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import roleInstanceSetScaleDialogStateInjectable from "./dialog-state.injectable";
import openRoleInstanceSetScaleDialogInjectable from "./open.injectable";
import roleInstanceSetScaleDialogClusterFrameChildComponentInjectable from "./roleinstanceset-scale-dialog-cluster-frame-child-component.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(openRoleInstanceSetScaleDialogInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleInstanceSetScaleDialogClusterFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleInstanceSetScaleDialogStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
