/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import roleInstanceScaleDialogStateInjectable from "./dialog-state.injectable";
import openRoleInstanceScaleDialogInjectable from "./open.injectable";
import roleInstanceScaleDialogClusterFrameChildComponentInjectable from "./roleinstance-scale-dialog-cluster-frame-child-component.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(openRoleInstanceScaleDialogInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleInstanceScaleDialogClusterFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleInstanceScaleDialogStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
